---
- name: Install, configure and autostart nginx
  hosts: all
  become: yes
  vars:
    - default_index: "<h1>Gubis Mátyás János</h1>"

  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Rewrite default index.html
      template:
        src: default_index.html.j2
        dest: /usr/share/nginx/html/index.html
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted